import React, { createContext, useContext, useState, useEffect, useRef } from 'react';
import { useAuth } from './AuthContext';
import { api } from '../lib/api';

type ThemeMode = 'light' | 'dark' | 'system';
type Language = 'en' | 'th' | 'zn';

export interface IntegrationKeys {
  googleClientId: string;
  googleClientSecret: string;
  lineChannelAccessToken: string;
  lineChannelSecret: string;
  fbAppId: string;
  fbAppSecret: string;
  fbPageAccessToken: string;
  fbPageId: string;
  instagramBusinessId: string;
  instagramAccessToken: string;
}

interface UserSettings {
  theme: ThemeMode;
  language: Language;
  primaryColor: string;
  accentColor: string;
  integrations: IntegrationKeys;
}

interface SettingsContextType {
  settings: UserSettings;
  theme: ThemeMode;
  setTheme: (mode: ThemeMode) => void;
  resolvedTheme: 'light' | 'dark';
  language: Language;
  setLanguage: (lang: Language) => void;
  primaryColor: string;
  setPrimaryColor: (c: string) => void;
  accentColor: string;
  setAccentColor: (c: string) => void;
  integrations: IntegrationKeys;
  setIntegrationKey: (key: keyof IntegrationKeys, value: string) => void;
  t: (key: string) => string;
  saveSettings: () => void;
  savedSuccess: boolean;
}

const DEFAULT_INTEGRATIONS: IntegrationKeys = {
  googleClientId: '',
  googleClientSecret: '',
  lineChannelAccessToken: '',
  lineChannelSecret: '',
  fbAppId: '',
  fbAppSecret: '',
  fbPageAccessToken: '',
  fbPageId: '',
  instagramBusinessId: '',
  instagramAccessToken: '',
};

const DEFAULT_SETTINGS: UserSettings = {
  theme: 'system',
  language: 'en',
  primaryColor: '#1D4ED8',
  accentColor: '#EAB308',
  integrations: { ...DEFAULT_INTEGRATIONS },
};

const translations: Record<Language, Record<string, string>> = {
  en: {
    'settings.title': 'Settings',
    'settings.subtitle': 'Configure your preferences, language, and appearance.',
    'settings.language': 'Language',
    'settings.theme': 'Theme',
    'settings.light': 'Light',
    'settings.dark': 'Dark',
    'settings.system': 'System',
    'settings.save': 'Save Settings',
    'settings.saved': 'Preferences saved successfully!',
    'settings.appearance': 'Appearance',
    'brand.primary': 'Primary Base Color',
    'brand.accent': 'Accent Color',
    'brand.palette': 'Brand Color Palette',
    'theme.light': 'Light Mode',
    'theme.dark': 'Dark Mode',
    'theme.system': 'System Default',
    'nav.stages': 'Sales Pipeline Stages',
    'page.dashboard': 'Executive Overview',
    'page.dashboard.desc': 'Welcome back, Sarah. Here is your sales pipeline status.',
    'page.inbox': 'Social Inbox',
    'page.inbox.desc': 'Unified inbox — Facebook, Instagram, LINE messages in one place.',
    'page.pipeline': 'Sales Pipeline & Kanban',
    'page.pipeline.desc': 'Manage deals, drag across stages, and close opportunities.',
    'page.contacts': 'Contacts & Accounts',
    'page.contacts.desc': 'Comprehensive CRM customer list and lead qualification.',
    'page.workflows': 'RelateFlows Automation Engine',
    'page.workflows.desc': 'Active triggers, automated email rules, and lead routing.',
    'page.analytics': 'Sales Analytics & Reports',
    'page.analytics.desc': 'Revenue breakdowns, win-rate metrics, and performance charts.',
    'page.calendar': 'Calendar',
    'page.calendar.desc': 'Manage appointments, meetings, and events.',
    'page.settings': 'System Settings',
    'page.settings.desc': 'Configure brand theme, user roles, integrations, and API keys.',
    'page.default': 'RelateFlows CRM',
    'page.default.desc': 'Customer Relationship Management',
    'status.scheduled': 'Scheduled',
    'status.completed': 'Completed',
    'status.cancelled': 'Cancelled',
    'status.pending': 'Pending',
    'status.quoted': 'Quoted',
    'status.ordered': 'Ordered',
    'status.delivered': 'Delivered',
    'status.active': 'Active',
    'status.paused': 'Paused',
    'status.inactive': 'Inactive',
    'guest.yes': 'Yes',
    'guest.no': 'No',
    'guest.awaiting': 'Awaiting',
    'guest.maybe': 'Maybe',
    'type.activity': 'Activity',
    'type.meeting': 'Meeting',
    'type.appointment': 'Appointment',
    'calendar.month': 'Month',
    'calendar.week': 'Week',
    'calendar.day': 'Day',
    'calendar.newEvent': 'New Event',
    'calendar.today': 'Today',
    'calendar.eventDetails': 'Event Details',
    'calendar.aboutEvent': 'About this event',
    'calendar.markCompleted': 'Mark as Completed',
    'calendar.copyDetails': 'Copy event details',
    'calendar.editEvent': 'Edit event',
    'calendar.deleteEvent': 'Delete event',
    'calendar.title': 'Title',
    'calendar.dateTime': 'Date & Time',
    'calendar.start': 'Start',
    'calendar.end': 'End',
    'calendar.eventType': 'Event Type',
    'calendar.status': 'Status',
    'calendar.location': 'Location',
    'calendar.description': 'Description',
    'calendar.assignMembers': 'Assign Team Members',
    'calendar.searchMembers': 'Search by name...',
    'calendar.cancel': 'Cancel',
    'calendar.create': 'Create Event',
    'calendar.update': 'Update Event',
    'calendar.guests': 'guests',
    'calendar.noGuests': 'No guests yet',
    'calendar.invitingTo': '{organizer} is inviting you to a scheduled {type}.',
    'calendar.linkedLead': 'Linked lead',
    'calendar.viewInGoogle': 'View in Google Calendar',
    'calendar.willSync': 'Will sync to Google Calendar',
    'calendar.syncOff': 'Google Calendar auto-sync is off',
    'calendar.membersAssigned': '{count} members assigned',
    'calendar.inviteGuests': 'Invite guests',
    'calendar.newEventDesc': 'Schedule a new appointment',
    'calendar.editEventDesc': 'Update appointment details',
    'calendar.noEvents': 'No events scheduled for this day',
    'calendar.upcomingFor': 'upcoming events for',
    'calendar.noMembers': 'No members found',
    'calendar.reminder': '10 min before',
    'calendar.nEvents': '{count} events',
    'calendar.invitedBy': 'is inviting you to a scheduled',
    'calendar.noLinkedLead': 'No linked lead',
    'calendar.linkLead': 'Link Lead',
    'integrations.title': 'Integrations & API Keys',
    'integrations.subtitle': 'Configure API credentials for external services. Saved keys are used by the backend at runtime.',
    'integrations.google': 'Google API',
    'integrations.google.desc': 'Client ID & Secret for Google Calendar sync',
    'integrations.google.clientId': 'Client ID',
    'integrations.google.clientSecret': 'Client Secret',
    'integrations.line': 'LINE Messaging API',
    'integrations.line.desc': 'Channel Access Token & Secret for LINE inbox',
    'integrations.line.token': 'Channel Access Token',
    'integrations.line.secret': 'Channel Secret',
    'integrations.facebook': 'Facebook Graph API',
    'integrations.facebook.desc': 'App credentials & Page token for Facebook inbox',
    'integrations.facebook.appId': 'App ID',
    'integrations.facebook.appSecret': 'App Secret',
    'integrations.facebook.pageToken': 'Page Access Token',
    'integrations.facebook.pageId': 'Page ID',
    'integrations.instagram': 'Instagram Graph API',
    'integrations.instagram.desc': 'Business Account ID & token for Instagram inbox',
    'integrations.instagram.businessId': 'Business Account ID',
    'integrations.instagram.token': 'Access Token',
    'integrations.saved': 'API keys saved securely with your settings.',
    // Sidebar
    'sidebar.dashboard': 'Dashboard',
    'sidebar.inbox': 'Social Inbox',
    'sidebar.pipeline': 'Sales Pipeline',
    'sidebar.contacts': 'Contacts & Leads',
    'sidebar.workflows': 'Workflows',
    'sidebar.tasks': 'Tasks',
    'sidebar.calendar': 'Calendar',
    'sidebar.analytics': 'Analytics',
    'sidebar.settings': 'Settings',
    'sidebar.mainMenu': 'Main Menu',
    'sidebar.newDeal': 'New Sales Deal',
    'sidebar.expand': 'Expand sidebar',
    'sidebar.collapse': 'Collapse sidebar',
    'sidebar.signOut': 'Sign Out',
    'sidebar.signOutTitle': 'Sign Out',
    'sidebar.signOutDesc': 'End your current session',
    'sidebar.signOutConfirm': 'Are you sure you want to sign out?',
    'sidebar.signOutDetail': 'You will need to log in again to access your pipeline, contacts, and workflows.',
    'sidebar.cancel': 'Cancel',
    'sidebar.q3Goals': 'Q3 Goals',
    'sidebar.pipelineForecast': 'Pipeline forecast reached {pct} of monthly quota.',
    'sidebar.target': 'Target: ${target}',
    // Header
    'header.searchPlaceholder': 'Search deals, contacts, companies...',
    'header.addContact': 'Add Contact',
    'header.notifications': 'Notifications',
    'header.markAllRead': 'Mark all as read',
    'header.notif.dealWon': 'Deal Closed Won!',
    'header.notif.dealWonDesc': 'Vanguard Pay signed contract ($210,000 ARR).',
    'header.notif.automation': 'RelateFlows Automation',
    'header.notif.automationDesc': 'Lead score trigger escalated David Miller (Apex Global).',
    'header.notif.meeting': 'Meeting Reminder',
    'header.notif.meetingDesc': 'Contract review with Catherine Hayes tomorrow at 10 AM.',
    // Allocation
    'allocation.title': 'Allocate Customer',
    'allocation.customer': 'Customer',
    'allocation.salesPerson': 'Sales Person',
    'allocation.selectSales': 'Select Sales Person...',
    'allocation.projectName': 'Project Name',
    'allocation.projectPlaceholder': 'e.g. RelateFlows Enterprise',
    'allocation.notes': 'Notes',
    'allocation.notesPlaceholder': 'Additional notes for the Sales person...',
    'allocation.reallocate': 'ต้องการ Allocated ใหม่',
    'allocation.reallocateDesc': 'If checked, a new allocation will be created instead of updating the existing one.',
    'allocation.reallocateSameSales': 'Will create new allocation. Previous: {project} → {sales}',
    'allocation.existingActive': 'Existing Active Allocation',
    'allocation.existingActiveDesc': 'This customer is already allocated to {sales} for project "{project}".',
    'allocation.history': 'Allocation History',
    'allocation.submitUpdate': 'Update Allocation',
    'allocation.submitCreate': 'Allocate to Sales',
    'allocation.submitReallocate': 'Allocate New (Re-allocation)',
    'allocation.prefilled': 'Pre-filled from existing allocation. Change if needed.',
    'allocation.reallocBadge': 'Re-alloc',
    'allocation.statusActive': 'active',
    'allocation.statusCompleted': 'completed',
    'allocation.statusCancelled': 'cancelled',
    // Tags
    'tags.title': 'Manage Tags',
    'tags.currentTags': 'Current Tags',
    'tags.noTags': 'No tags assigned yet',
    'tags.searchTags': 'Search tags...',
    'tags.allTags': 'All Tags',
    'tags.createNew': 'Create New Tag',
    'tags.createTag': 'Create Tag',
    'tags.tagName': 'Tag name...',
    'tags.cancel': 'Cancel',
    'tags.noTagsFound': 'No tags found. Click below to create one.',
    'tags.allAssigned': 'All tags assigned',
    // Inbox
    'inbox.title': 'Inbox',
    'inbox.unread': '{count} unread',
    'inbox.conversations': '{count} of {total} conversations',
    'inbox.allocated': 'Allocated',
    'inbox.unassigned': 'Unassigned',
    'inbox.allocate': 'Allocate',
    'inbox.reallocate': 'Re-allocate',
    'inbox.tags': 'Tags',
    'inbox.replyAs': 'Replying as {name}',
    'inbox.typeMessage': 'Type a message...',
    'inbox.noProducts': 'No products yet',
    'inbox.addProduct': 'Add',
    'inbox.products': 'Products',
    'inbox.items': 'items',
    'inbox.selectConversation': 'Select a conversation',
    'inbox.totalValue': 'Total Value',
    'inbox.save': 'Save',
    'inbox.cancel': 'Cancel',
    'inbox.noCategory': 'No category',
    'inbox.productName': 'Product name',
    'inbox.qty': 'Qty',
    'inbox.price': 'Price',
    'inbox.description': 'Description',
    'inbox.notes': 'Notes',
    'inbox.noProductsHint': 'Click "Add" to record what this customer wants',
    'inbox.unknown': 'Unknown',
    // Tasks
    'tasks.title': 'Tasks',
    'tasks.desc': 'Manage your to-dos, follow-ups, and assignments.',
    'tasks.openCompleted': '{open} open · {completed} completed',
    'tasks.search': 'Search tasks...',
    'tasks.filter.all': 'All',
    'tasks.filter.todo': 'To Do',
    'tasks.filter.inProgress': 'In Progress',
    'tasks.filter.done': 'Done',
    'tasks.addTask': 'Add Task',
    'tasks.column.todo': 'To Do',
    'tasks.column.inProgress': 'In Progress',
    'tasks.column.done': 'Done',
    'tasks.empty': 'No tasks',
    'tasks.priority.low': 'Low',
    'tasks.priority.medium': 'Medium',
    'tasks.priority.high': 'High',
    'tasks.modal.newTask': 'New Task',
    'tasks.modal.title': 'Task title *',
    'tasks.modal.description': 'Description (optional)',
    'tasks.modal.priority': 'Priority',
    'tasks.modal.dueDate': 'Due Date',
    'tasks.modal.assignee': 'Assignee name (optional)',
    'tasks.modal.cancel': 'Cancel',
    'tasks.modal.create': 'Create Task',
    'tasks.me': 'Me',
    // Pipeline
    'pipeline.title': 'Sales Pipeline & Kanban',
    'pipeline.desc': 'Manage deals, drag across stages, and close opportunities.',
    // Contacts
    'contacts.title': 'Contacts & Accounts',
    'contacts.desc': 'Comprehensive CRM customer list and lead qualification.',
    'contacts.directory': 'Contacts & Accounts Directory',
    'contacts.total': 'Total Contacts: {count} \u2022 High Lead Score (>80): {high} contacts',
    'contacts.stage': 'Stage:',
    'contacts.stage.all': 'All Stages',
    'contacts.stage.customers': 'Customers',
    'contacts.stage.opportunities': 'Opportunities',
    'contacts.stage.sql': 'SQL (Sales Qualified)',
    'contacts.stage.mql': 'MQL (Marketing Qualified)',
    'contacts.stage.leads': 'Leads',
    'contacts.addContact': 'Add Contact',
    'contacts.table.name': 'Contact Name & Role',
    'contacts.table.company': 'Company',
    'contacts.table.stage': 'Lifecycle Stage',
    'contacts.table.score': 'Lead Score',
    'contacts.table.value': 'Total Value',
    'contacts.table.contacted': 'Last Contacted',
    'contacts.table.actions': 'Actions',
    'contacts.empty': 'No contacts found matching your query.',
    'contacts.viewProfile': 'View Profile',
    // Dashboard
    'dashboard.pipelineFunnel': 'Pipeline Funnel Distribution',
    'dashboard.pipelineFunnel.desc': 'Live breakdown of deals by sales stage',
    'dashboard.viewKanban': 'View All Kanban',
    'dashboard.stage.leadIn': 'Lead In',
    'dashboard.stage.contacted': 'Contacted',
    'dashboard.stage.proposal': 'Proposal',
    'dashboard.stage.negotiation': 'Negotiation',
    'dashboard.stage.closedWon': 'Closed Won',
    'dashboard.stage.closedLost': 'Closed Lost',
    'dashboard.stage.deals': '{v} deals',
    'dashboard.topDeals': 'Top High Priority Deals',
    'dashboard.winProb': '{prob}% Win Prob',
    'dashboard.triggers': 'RelateFlows Triggers',
    'dashboard.manageAll': 'Manage All',
    'dashboard.runs': '{count} runs',
    'dashboard.recentActivity': 'Recent CRM Activity',
    // Pipeline
    'pipeline.zoom.day': 'Day',
    'pipeline.zoom.week': 'Week',
    'pipeline.zoom.month': 'Month',
    'pipeline.zoom.year': 'Year',
    'pipeline.zoom.all': 'All',
    'pipeline.viewToggle.kanban': 'Kanban',
    'pipeline.viewToggle.gantt': 'Gantt',
    'pipeline.filter.high': 'High',
    'pipeline.filter.medium': 'Medium',
    'pipeline.filter.low': 'Low',
    'pipeline.addDeal': 'Add Deal',
    'pipeline.gantt': 'Deal Timeline (Gantt)',
    'pipeline.gantt.desc': 'Click a bar to view deal details \u00b7 Plan (gray) vs Actual (colored) by stage progress',
    'pipeline.noDeals': 'No deals to display',
    'pipeline.plan': 'Plan (full timeline)',
    'pipeline.actual': 'Actual (stage progress)',
    'pipeline.progress': 'Progress = current stage position / total stages',
    'pipeline.dropHere': 'Drop deals here',
    'pipeline.tooltip.company': 'Company',
    'pipeline.tooltip.value': 'Value',
    'pipeline.tooltip.contact': 'Contact',
    'pipeline.tooltip.stage': 'Stage',
    // Analytics
    'analytics.totalArr': 'Total Pipeline ARR',
    'analytics.yoyGrowth': '+18.4% YoY Growth',
    'analytics.closedWon': 'Closed Won Revenue',
    'analytics.q3Target': '60% of Q3 Target',
    'analytics.winRate': 'Overall Win Rate',
    'analytics.benchmark': 'Benchmark: 25%',
    'analytics.cycleLength': 'Sales Cycle Length',
    'analytics.cycleDays': '21 Days',
    'analytics.faster': '4 days faster with RelateFlows',
    'analytics.monthlyRevenue': 'Monthly Revenue & Forecast',
    'analytics.monthlyRevenue.desc': 'Historical performance & Q3 forecast breakdown',
    'analytics.q3': 'Q3 2026',
    'analytics.leadSource': 'Lead Source Attribution',
    'analytics.leaderboard': 'Sales Team Leaderboard (Q3)',
    'analytics.dealsWon': '{count} deals won',
    // CS Queue
    'sidebar.csQueue': 'CS Queue',
    'page.csQueue': 'CS Queue',
    'page.csQueue.desc': 'Customer support chat queue and team management',
    'csQueue.title': 'Customer Support Queue',
    'csQueue.subtitle': '{waiting} waiting \u00b7 {active} active',
    'csQueue.userInfo': '{name} \u00b7 {role}',
    'csQueue.failedClaim': 'Failed to claim chat',
    'csQueue.tab.queue': 'Queue ({count})',
    'csQueue.tab.myChats': 'My Chats ({count})',
    'csQueue.tab.team': 'Team ({count} online)',
    'csQueue.tab.performance': 'Performance',
    'csQueue.refresh': 'Refresh',
    'csQueue.closeChat': 'Close Chat',
    'csQueue.noMessages': 'No messages yet',
    'csQueue.typeResponse': 'Type your response...',
    'csQueue.status.all': 'All',
    'csQueue.status.waiting': 'Waiting',
    'csQueue.status.assigned': 'Assigned',
    'csQueue.status.active': 'Active',
    'csQueue.status.closed': 'Closed',
    'csQueue.sessions': '{count} sessions',
    'csQueue.queueEmpty': 'No chats in queue',
    'csQueue.view': 'View',
    'csQueue.claim': 'Claim',
    'csQueue.myChatsEmpty': 'No active chats assigned to you',
    'csQueue.messages': '{count} messages',
    'csQueue.open': 'Open',
    'csQueue.online': 'Online',
    'csQueue.offline': 'Offline',
    'csQueue.activeChats': 'Active chats',
    'csQueue.todaySchedule': "Today's schedule",
    'csQueue.dayOff': 'Day off',
    'csQueue.noTeam': 'No CS team members found',
    'csQueue.performance': 'Last 7 Days Performance',
    'csQueue.table.agent': 'Agent',
    'csQueue.table.totalChats': 'Total Chats',
    'csQueue.table.responded': 'Responded',
    'csQueue.table.avgResponse': 'Avg Response',
    'csQueue.table.closed': 'Closed',
    'csQueue.table.hoursSpent': 'Hours Spent',
    'csQueue.min': '{count} min',
    'csQueue.hrs': '{count} hrs',
    'csQueue.unknown': 'Unknown',
    'csQueue.noPerformance': 'No performance data yet',
  },
  th: {
    'settings.title': 'ตั้งค่า',
    'settings.subtitle': 'กำหนดค่ากำหนด ภาษา และลักษณะที่ปรากฏ',
    'settings.language': 'ภาษา',
    'settings.theme': 'ธีม',
    'settings.light': 'สว่าง',
    'settings.dark': 'มืด',
    'settings.system': 'ตามระบบ',
    'settings.save': 'บันทึกการตั้งค่า',
    'settings.saved': 'บันทึกการตั้งค่าเรียบร้อยแล้ว!',
    'settings.appearance': 'ลักษณะที่ปรากฏ',
    'brand.primary': 'สีหลัก',
    'brand.accent': 'สีเน้น',
    'brand.palette': 'จานสีแบรนด์',
    'theme.light': 'โหมดสว่าง',
    'theme.dark': 'โหมดมืด',
    'theme.system': 'ค่าเริ่มต้นของระบบ',
    'nav.stages': 'ขั้นตอนการขาย',
    'page.dashboard': 'ภาพรวมผู้บริหาร',
    'page.dashboard.desc': 'ยินดีต้อนรับกลับ Sarah นี่คือสถานะไปป์ไลน์การขายของคุณ',
    'page.inbox': 'กล่องข้อความรวม',
    'page.inbox.desc': 'กล่องข้อความรวม — Facebook, Instagram, LINE ข้อความทั้งหมดในที่เดียว',
    'page.pipeline': 'ไปป์ไลน์การขาย & Kanban',
    'page.pipeline.desc': 'จัดการดีล ลากข้ามขั้นตอน และปิดการขาย',
    'page.contacts': 'ผู้ติดต่อและบัญชี',
    'page.contacts.desc': 'รายชื่อลูกค้า CRM และการคัดกรองลีด',
    'page.workflows': 'RelateFlows อัตโนมัติ',
    'page.workflows.desc': 'ทริกเกอร์ กฎอีเมลอัตโนมัติ และการจัดเส้นทางลีด',
    'page.analytics': 'รายงานการวิเคราะห์การขาย',
    'page.analytics.desc': 'รายละเอียดรายได้ เมตริกอัตราชนะ และกราฟประสิทธิภาพ',
    'page.calendar': 'ปฏิทิน',
    'page.calendar.desc': 'จัดการการนัดหมาย การประชุม และกิจกรรมต่างๆ',
    'page.settings': 'การตั้งค่าระบบ',
    'page.settings.desc': 'กำหนดค่าธีมแบรนด์ บทบาทผู้ใช้ การเชื่อมต่อ และคีย์ API',
    'page.default': 'RelateFlows CRM',
    'page.default.desc': 'การจัดการความสัมพันธ์ลูกค้า',
    'status.scheduled': 'นัดหมายแล้ว',
    'status.completed': 'เสร็จสิ้น',
    'status.cancelled': 'ยกเลิก',
    'status.pending': 'รอดำเนินการ',
    'status.quoted': 'เสนอราคา',
    'status.ordered': 'สั่งซื้อแล้ว',
    'status.delivered': 'ส่งแล้ว',
    'status.active': 'กำลังทำงาน',
    'status.paused': 'หยุดชั่วคราว',
    'status.inactive': 'ไม่ได้ใช้งาน',
    'guest.yes': 'ใช่',
    'guest.no': 'ไม่',
    'guest.awaiting': 'รอตอบรับ',
    'guest.maybe': 'บางที',
    'type.activity': 'กิจกรรม',
    'type.meeting': 'ประชุม',
    'type.appointment': 'นัดหมาย',
    'calendar.month': 'เดือน',
    'calendar.week': 'สัปดาห์',
    'calendar.day': 'วัน',
    'calendar.newEvent': 'กิจกรรมใหม่',
    'calendar.today': 'วันนี้',
    'calendar.eventDetails': 'รายละเอียดกิจกรรม',
    'calendar.aboutEvent': 'เกี่ยวกับกิจกรรมนี้',
    'calendar.markCompleted': 'ทำเครื่องหมายว่าเสร็จสิ้น',
    'calendar.copyDetails': 'คัดลอกรายละเอียด',
    'calendar.editEvent': 'แก้ไขกิจกรรม',
    'calendar.deleteEvent': 'ลบกิจกรรม',
    'calendar.title': 'ชื่อ',
    'calendar.dateTime': 'วันที่และเวลา',
    'calendar.start': 'เริ่ม',
    'calendar.end': 'สิ้นสุด',
    'calendar.eventType': 'ประเภทกิจกรรม',
    'calendar.status': 'สถานะ',
    'calendar.location': 'สถานที่',
    'calendar.description': 'คำอธิบาย',
    'calendar.assignMembers': 'กำหนดสมาชิกทีม',
    'calendar.searchMembers': 'ค้นหาด้วยชื่อ...',
    'calendar.cancel': 'ยกเลิก',
    'calendar.create': 'สร้างกิจกรรม',
    'calendar.update': 'อัปเดตกิจกรรม',
    'calendar.guests': 'คน',
    'calendar.noGuests': 'ยังไม่มีผู้เข้าร่วม',
    'calendar.invitingTo': '{organizer} กำลังเชิญคุณเข้าร่วม {type}',
    'calendar.linkedLead': 'ลีดที่เกี่ยวข้อง',
    'calendar.viewInGoogle': 'ดูใน Google ปฏิทิน',
    'calendar.willSync': 'จะซิงค์กับ Google ปฏิทิน',
    'calendar.syncOff': 'ปิดการซิงค์อัตโนมัติกับ Google ปฏิทิน',
    'calendar.membersAssigned': '{count} คนที่ได้รับมอบหมาย',
    'calendar.inviteGuests': 'เชิญผู้เข้าร่วม',
    'calendar.newEventDesc': 'กำหนดการนัดหมายใหม่',
    'calendar.editEventDesc': 'อัปเดตรายละเอียดการนัดหมาย',
    'calendar.noEvents': 'ไม่มีกิจกรรมในวันนี้',
    'calendar.upcomingFor': 'กิจกรรมที่จะมาถึงของ',
    'calendar.noMembers': 'ไม่พบสมาชิก',
    'calendar.reminder': '10 นาทีก่อน',
    'calendar.nEvents': '{count} กิจกรรม',
    'calendar.invitedBy': 'กำลังเชิญคุณเข้าร่วม',
    'calendar.noLinkedLead': 'ไม่มีลีดที่เกี่ยวข้อง',
    'calendar.linkLead': 'เชื่อมโยงลีด',
    'integrations.title': 'การเชื่อมต่อและคีย์ API',
    'integrations.subtitle': 'กำหนดค่า API สำหรับบริการภายนอก คีย์จะถูกใช้โดยระบบหลังบ้าน',
    'integrations.google': 'Google API',
    'integrations.google.desc': 'Client ID และ Secret สำหรับซิงค์ Google ปฏิทิน',
    'integrations.google.clientId': 'Client ID',
    'integrations.google.clientSecret': 'Client Secret',
    'integrations.line': 'LINE Messaging API',
    'integrations.line.desc': 'Channel Access Token และ Secret สำหรับ LINE inbox',
    'integrations.line.token': 'Channel Access Token',
    'integrations.line.secret': 'Channel Secret',
    'integrations.facebook': 'Facebook Graph API',
    'integrations.facebook.desc': 'App ID, Secret, และ Page Token สำหรับ Facebook inbox',
    'integrations.facebook.appId': 'App ID',
    'integrations.facebook.appSecret': 'App Secret',
    'integrations.facebook.pageToken': 'Page Access Token',
    'integrations.facebook.pageId': 'Page ID',
    'integrations.instagram': 'Instagram Graph API',
    'integrations.instagram.desc': 'Business Account ID และ Token สำหรับ Instagram inbox',
    'integrations.instagram.businessId': 'Business Account ID',
    'integrations.instagram.token': 'Access Token',
    'integrations.saved': 'บันทึกคีย์ API เรียบร้อยแล้ว',
    // Sidebar
    'sidebar.dashboard': 'แดชบอร์ด',
    'sidebar.inbox': 'กล่องข้อความ',
    'sidebar.pipeline': 'ไปป์ไลน์การขาย',
    'sidebar.contacts': 'ผู้ติดต่อและลีด',
    'sidebar.workflows': 'เวิร์กโฟลว์',
    'sidebar.tasks': 'งาน',
    'sidebar.calendar': 'ปฏิทิน',
    'sidebar.analytics': 'วิเคราะห์',
    'sidebar.settings': 'ตั้งค่า',
    'sidebar.mainMenu': 'เมนูหลัก',
    'sidebar.newDeal': 'ดีลใหม่',
    'sidebar.expand': 'ขยายไซด์บาร์',
    'sidebar.collapse': 'ย่อไซด์บาร์',
    'sidebar.signOut': 'ออกจากระบบ',
    'sidebar.signOutTitle': 'ออกจากระบบ',
    'sidebar.signOutDesc': 'สิ้นสุดเซสชันปัจจุบัน',
    'sidebar.signOutConfirm': 'คุณแน่ใจหรือว่าต้องการออกจากระบบ?',
    'sidebar.signOutDetail': 'คุณจะต้องเข้าสู่ระบบอีกครั้งเพื่อเข้าถึงไปป์ไลน์ ผู้ติดต่อ และเวิร์กโฟลว์',
    'sidebar.cancel': 'ยกเลิก',
    'sidebar.q3Goals': 'เป้าหมาย Q3',
    'sidebar.pipelineForecast': 'ไปป์ไลน์ถึง {pct} ของโควต้ารายเดือน',
    'sidebar.target': 'เป้า: ${target}',
    // Header
    'header.searchPlaceholder': 'ค้นหาดีล ผู้ติดต่อ บริษัท...',
    'header.addContact': 'เพิ่มผู้ติดต่อ',
    'header.notifications': 'การแจ้งเตือน',
    'header.markAllRead': 'ทำเครื่องหมายว่าอ่านแล้ว',
    'header.notif.dealWon': 'ปิดดีลสำเร็จ!',
    'header.notif.dealWonDesc': 'Vanguard Pay เซ็นสัญญา ($210,000 ARR)',
    'header.notif.automation': 'RelateFlows อัตโนมัติ',
    'header.notif.automationDesc': 'Lead score trigger แจ้งเตือน David Miller (Apex Global)',
    'header.notif.meeting': 'เตือนความจำการประชุม',
    'header.notif.meetingDesc': 'ตรวจสอบสัญญากับ Catherine Hayes พรุ่งนี้ 10 โมง',
    // Allocation
    'allocation.title': 'จัดสรรลูกค้า',
    'allocation.customer': 'ลูกค้า',
    'allocation.salesPerson': 'พนักงานขาย',
    'allocation.selectSales': 'เลือกพนักงานขาย...',
    'allocation.projectName': 'ชื่อโครงการ',
    'allocation.projectPlaceholder': 'เช่น RelateFlows Enterprise',
    'allocation.notes': 'บันทึก',
    'allocation.notesPlaceholder': 'บันทึกเพิ่มเติมสำหรับพนักงานขาย...',
    'allocation.reallocate': 'ต้องการ Allocated ใหม่',
    'allocation.reallocateDesc': 'หากเลือก จะสร้างการจัดสรรใหม่แทนที่จะอัปเดตของเดิม',
    'allocation.reallocateSameSales': 'จะสร้างการจัดสรรใหม่ ก่อนหน้า: {project} → {sales}',
    'allocation.existingActive': 'มีการจัดสรรที่ใช้งานอยู่',
    'allocation.existingActiveDesc': 'ลูกค้ารายนี้ถูกจัดสรรให้ {sales} สำหรับโครงการ "{project}" แล้ว',
    'allocation.history': 'ประวัติการจัดสรร',
    'allocation.submitUpdate': 'อัปเดตการจัดสรร',
    'allocation.submitCreate': 'จัดสรรให้พนักงานขาย',
    'allocation.submitReallocate': 'จัดสรรใหม่ (Re-allocation)',
    'allocation.prefilled': 'ข้อมูลจากเดิม เปลี่ยนได้หากต้องการ',
    'allocation.reallocBadge': 'จัดสรรใหม่',
    'allocation.statusActive': 'กำลังใช้งาน',
    'allocation.statusCompleted': 'เสร็จสิ้น',
    'allocation.statusCancelled': 'ยกเลิก',
    // Tags
    'tags.title': 'จัดการแท็ก',
    'tags.currentTags': 'แท็กปัจจุบัน',
    'tags.noTags': 'ยังไม่มีแท็ก',
    'tags.searchTags': 'ค้นหาแท็ก...',
    'tags.allTags': 'แท็กทั้งหมด',
    'tags.createNew': 'สร้างแท็กใหม่',
    'tags.createTag': 'สร้างแท็ก',
    'tags.tagName': 'ชื่อแท็ก...',
    'tags.cancel': 'ยกเลิก',
    'tags.noTagsFound': 'ไม่พบแท็ก คลิกด้านล่างเพื่อสร้าง',
    'tags.allAssigned': 'แท็กทั้งหมดถูกใช้งานแล้ว',
    // Inbox
    'inbox.title': 'กล่องข้อความ',
    'inbox.unread': '{count} ยังไม่ได้อ่าน',
    'inbox.conversations': '{count} จาก {total} การสนทนา',
    'inbox.allocated': 'จัดสรรแล้ว',
    'inbox.unassigned': 'ยังไม่ได้จัดสรร',
    'inbox.allocate': 'จัดสรร',
    'inbox.reallocate': 'จัดสรรใหม่',
    'inbox.tags': 'แท็ก',
    'inbox.replyAs': 'ตอบกลับเป็น {name}',
    'inbox.typeMessage': 'พิมพ์ข้อความ...',
    'inbox.noProducts': 'ยังไม่มีสินค้า',
    'inbox.addProduct': 'เพิ่ม',
    'inbox.products': 'สินค้า',
    'inbox.items': 'รายการ',
    'inbox.selectConversation': 'เลือกการสนทนา',
    'inbox.totalValue': 'มูลค่ารวม',
    'inbox.save': 'บันทึก',
    'inbox.cancel': 'ยกเลิก',
    'inbox.noCategory': 'ไม่มีหมวดหมู่',
    'inbox.productName': 'ชื่อสินค้า',
    'inbox.qty': 'จำนวน',
    'inbox.price': 'ราคา',
    'inbox.description': 'รายละเอียด',
    'inbox.notes': 'หมายเหตุ',
    'inbox.noProductsHint': 'คลิก "เพิ่ม" เพื่อบันทึกสิ่งที่ลูกค้าต้องการ',
    'inbox.unknown': 'ไม่ทราบ',
    // Tasks
    'tasks.title': 'งาน',
    'tasks.desc': 'จัดการสิ่งที่ต้องทำ งานติดตาม และงานที่ได้รับมอบหมาย',
    'tasks.openCompleted': '{open} เปิด · {completed} เสร็จแล้ว',
    'tasks.search': 'ค้นหางาน...',
    'tasks.filter.all': 'ทั้งหมด',
    'tasks.filter.todo': 'สิ่งที่ต้องทำ',
    'tasks.filter.inProgress': 'กำลังดำเนินการ',
    'tasks.filter.done': 'เสร็จแล้ว',
    'tasks.addTask': 'เพิ่มงาน',
    'tasks.column.todo': 'สิ่งที่ต้องทำ',
    'tasks.column.inProgress': 'กำลังดำเนินการ',
    'tasks.column.done': 'เสร็จแล้ว',
    'tasks.empty': 'ไม่มีงาน',
    'tasks.priority.low': 'ต่ำ',
    'tasks.priority.medium': 'ปานกลาง',
    'tasks.priority.high': 'สูง',
    'tasks.modal.newTask': 'งานใหม่',
    'tasks.modal.title': 'ชื่องาน *',
    'tasks.modal.description': 'คำอธิบาย (ไม่บังคับ)',
    'tasks.modal.priority': 'ความสำคัญ',
    'tasks.modal.dueDate': 'วันที่ครบกำหนด',
    'tasks.modal.assignee': 'ชื่อผู้รับผิดชอบ (ไม่บังคับ)',
    'tasks.modal.cancel': 'ยกเลิก',
    'tasks.modal.create': 'สร้างงาน',
    'tasks.me': 'ฉัน',
    // Pipeline
    'pipeline.title': 'ไปป์ไลน์การขายและคัมบัง',
    'pipeline.desc': 'จัดการดีล ลากข้ามขั้นตอน และปิดการขาย',
    // Contacts
    'contacts.title': 'ผู้ติดต่อและบัญชี',
    'contacts.desc': 'รายชื่อลูกค้า CRM และการคัดกรองลีดที่ครอบคลุม',
    'contacts.directory': 'ไดเรกทอรีผู้ติดต่อและบัญชี',
    'contacts.total': 'ผู้ติดต่อทั้งหมด: {count} \u2022 คะแนนนำสูง (>80): {high} ราย',
    'contacts.stage': 'ขั้นตอน:',
    'contacts.stage.all': 'ทุกขั้นตอน',
    'contacts.stage.customers': 'ลูกค้า',
    'contacts.stage.opportunities': 'โอกาส',
    'contacts.stage.sql': 'SQL (คัดกรองแล้ว)',
    'contacts.stage.mql': 'MQL (คัดกรองการตลาด)',
    'contacts.stage.leads': 'ลีด',
    'contacts.addContact': 'เพิ่มผู้ติดต่อ',
    'contacts.table.name': 'ชื่อและบทบาท',
    'contacts.table.company': 'บริษัท',
    'contacts.table.stage': 'ขั้นตอนวงจร',
    'contacts.table.score': 'คะแนนลีด',
    'contacts.table.value': 'มูลค่ารวม',
    'contacts.table.contacted': 'ติดต่อล่าสุด',
    'contacts.table.actions': 'การดำเนินการ',
    'contacts.empty': 'ไม่พบผู้ติดต่อที่ตรงกับคำค้นหา',
    'contacts.viewProfile': 'ดูโปรไฟล์',
    // Dashboard
    'dashboard.pipelineFunnel': 'การกระจายไปป์ไลน์',
    'dashboard.pipelineFunnel.desc': 'รายละเอียดดีลตามขั้นตอนขายแบบเรียลไทม์',
    'dashboard.viewKanban': 'ดู Kanban ทั้งหมด',
    'dashboard.stage.leadIn': 'ลีดเข้า',
    'dashboard.stage.contacted': 'ติดต่อแล้ว',
    'dashboard.stage.proposal': 'เสนอราคา',
    'dashboard.stage.negotiation': 'เจรจา',
    'dashboard.stage.closedWon': 'ปิดสำเร็จ',
    'dashboard.stage.closedLost': 'ปิดไม่สำเร็จ',
    'dashboard.stage.deals': '{v} ดีล',
    'dashboard.topDeals': 'ดีลสำคัญสูงสุด',
    'dashboard.winProb': '{prob}% โอกาสชนะ',
    'dashboard.triggers': 'ทริกเกอร์ RelateFlows',
    'dashboard.manageAll': 'จัดการทั้งหมด',
    'dashboard.runs': '{count} ครั้ง',
    'dashboard.recentActivity': 'กิจกรรม CRM ล่าสุด',
    // Pipeline
    'pipeline.zoom.day': 'วัน',
    'pipeline.zoom.week': 'สัปดาห์',
    'pipeline.zoom.month': 'เดือน',
    'pipeline.zoom.year': 'ปี',
    'pipeline.zoom.all': 'ทั้งหมด',
    'pipeline.viewToggle.kanban': 'คัมบัง',
    'pipeline.viewToggle.gantt': 'แกนต์',
    'pipeline.filter.high': 'สูง',
    'pipeline.filter.medium': 'ปานกลาง',
    'pipeline.filter.low': 'ต่ำ',
    'pipeline.addDeal': 'เพิ่มดีล',
    'pipeline.gantt': 'ไทม์ไลน์ดีล (แกนต์)',
    'pipeline.gantt.desc': 'คลิกแท่งเพื่อดูรายละเอียดดีล \u00b7 แผน (สีเทา) เทียบกับจริง (สี) ตามความคืบหน้าขั้นตอน',
    'pipeline.noDeals': 'ไม่มีดีลที่จะแสดง',
    'pipeline.plan': 'แผน (ไทม์ไลน์เต็ม)',
    'pipeline.actual': 'จริง (ความคืบหน้าขั้นตอน)',
    'pipeline.progress': 'ความคืบหน้า = ตำแหน่งขั้นตอนปัจจุบัน / จำนวนขั้นตอนทั้งหมด',
    'pipeline.dropHere': 'วางดีลที่นี่',
    'pipeline.tooltip.company': 'บริษัท',
    'pipeline.tooltip.value': 'มูลค่า',
    'pipeline.tooltip.contact': 'ผู้ติดต่อ',
    'pipeline.tooltip.stage': 'ขั้นตอน',
    // Analytics
    'analytics.totalArr': 'มูลค่า ARR รวม',
    'analytics.yoyGrowth': '+18.4% เติบโตเทียบปีก่อน',
    'analytics.closedWon': 'รายได้ที่ปิดสำเร็จ',
    'analytics.q3Target': '60% ของเป้าหมาย Q3',
    'analytics.winRate': 'อัตราชนะโดยรวม',
    'analytics.benchmark': 'เกณฑ์มาตรฐาน: 25%',
    'analytics.cycleLength': 'ระยะเวลาวงจรขาย',
    'analytics.cycleDays': '21 วัน',
    'analytics.faster': 'เร็วขึ้น 4 วันด้วย RelateFlows',
    'analytics.monthlyRevenue': 'รายได้รายเดือนและพยากรณ์',
    'analytics.monthlyRevenue.desc': 'ผลงานย้อนหลังและรายละเอียดพยากรณ์ Q3',
    'analytics.q3': 'Q3 2026',
    'analytics.leadSource': 'ที่มาของลีด',
    'analytics.leaderboard': 'อันดับทีมขาย (Q3)',
    'analytics.dealsWon': '{count} ดีลที่ปิดสำเร็จ',
    // CS Queue
    'sidebar.csQueue': 'คิว CS',
    'page.csQueue': 'คิว CS',
    'page.csQueue.desc': 'คิวแชทฝ่ายบริการลูกค้าและการจัดการทีม',
    'csQueue.title': 'คิวฝ่ายบริการลูกค้า',
    'csQueue.subtitle': '{waiting} รอ \u00b7 {active} กำลังใช้งาน',
    'csQueue.userInfo': '{name} \u00b7 {role}',
    'csQueue.failedClaim': 'ไม่สามารถรับแชทได้',
    'csQueue.tab.queue': 'คิว ({count})',
    'csQueue.tab.myChats': 'แชทของฉัน ({count})',
    'csQueue.tab.team': 'ทีม ({count} ออนไลน์)',
    'csQueue.tab.performance': 'ประสิทธิภาพ',
    'csQueue.refresh': 'รีเฟรช',
    'csQueue.closeChat': 'ปิดแชท',
    'csQueue.noMessages': 'ยังไม่มีข้อความ',
    'csQueue.typeResponse': 'พิมพ์คำตอบของคุณ...',
    'csQueue.status.all': 'ทั้งหมด',
    'csQueue.status.waiting': 'รอ',
    'csQueue.status.assigned': 'มอบหมายแล้ว',
    'csQueue.status.active': 'กำลังใช้งาน',
    'csQueue.status.closed': 'ปิดแล้ว',
    'csQueue.sessions': '{count} เซสชัน',
    'csQueue.queueEmpty': 'ไม่มีแชทในคิว',
    'csQueue.view': 'ดู',
    'csQueue.claim': 'รับ',
    'csQueue.myChatsEmpty': 'ไม่มีแชทที่มอบหมายให้คุณ',
    'csQueue.messages': '{count} ข้อความ',
    'csQueue.open': 'เปิด',
    'csQueue.online': 'ออนไลน์',
    'csQueue.offline': 'ออฟไลน์',
    'csQueue.activeChats': 'แชทที่กำลังใช้งาน',
    'csQueue.todaySchedule': "ตารางวันนี้",
    'csQueue.dayOff': 'วันหยุด',
    'csQueue.noTeam': 'ไม่พบสมาชิกทีม CS',
    'csQueue.performance': 'ประสิทธิภาพ 7 วันที่ผ่านมา',
    'csQueue.table.agent': 'ตัวแทน',
    'csQueue.table.totalChats': 'แชททั้งหมด',
    'csQueue.table.responded': 'ตอบกลับ',
    'csQueue.table.avgResponse': 'เวลาเฉลี่ยตอบกลับ',
    'csQueue.table.closed': 'ปิด',
    'csQueue.table.hoursSpent': 'ชั่วโมง',
    'csQueue.min': '{count} นาที',
    'csQueue.hrs': '{count} ชม.',
    'csQueue.unknown': 'ไม่ทราบ',
    'csQueue.noPerformance': 'ยังไม่มีข้อมูลประสิทธิภาพ',
  },
  zn: {
    'settings.title': '设置',
    'settings.subtitle': '配置您的偏好、语言和外观。',
    'settings.language': '语言',
    'settings.theme': '主题',
    'settings.light': '明亮',
    'settings.dark': '深色',
    'settings.system': '跟随系统',
    'settings.save': '保存设置',
    'settings.saved': '设置已成功保存！',
    'settings.appearance': '外观',
    'brand.primary': '主色调',
    'brand.accent': '强调色',
    'brand.palette': '品牌调色板',
    'theme.light': '浅色模式',
    'theme.dark': '深色模式',
    'theme.system': '系统默认',
    'nav.stages': '销售阶段',
    'page.dashboard': '高管概览',
    'page.dashboard.desc': '欢迎回来，Sarah。这是您的销售管道状态。',
    'page.inbox': '社交收件箱',
    'page.inbox.desc': '统一收件箱 — Facebook, Instagram, LINE 消息汇总一处。',
    'page.pipeline': '销售管道与看板',
    'page.pipeline.desc': '管理交易，拖拽跨越阶段，并关闭机会。',
    'page.contacts': '联系人与账户',
    'page.contacts.desc': '全面的CRM客户列表和潜在客户资格认定。',
    'page.workflows': 'RelateFlows 自动化引擎',
    'page.workflows.desc': '活跃触发器、自动邮件规则和潜在客户路由。',
    'page.analytics': '销售分析与报告',
    'page.analytics.desc': '收入细分、胜率指标和绩效图表。',
    'page.calendar': '日历',
    'page.calendar.desc': '管理约会、会议和活动。',
    'page.settings': '系统设置',
    'page.settings.desc': '配置品牌主题、用户角色、集成和API密钥。',
    'page.default': 'RelateFlows CRM',
    'page.default.desc': '客户关系管理',
    'status.scheduled': '已安排',
    'status.completed': '已完成',
    'status.cancelled': '已取消',
    'status.pending': '待处理',
    'status.quoted': '已报价',
    'status.ordered': '已订购',
    'status.delivered': '已交付',
    'status.active': '活跃中',
    'status.paused': '已暂停',
    'status.inactive': '未激活',
    'guest.yes': '是',
    'guest.no': '否',
    'guest.awaiting': '待回复',
    'guest.maybe': '可能',
    'type.activity': '活动',
    'type.meeting': '会议',
    'type.appointment': '约会',
    'calendar.month': '月',
    'calendar.week': '周',
    'calendar.day': '日',
    'calendar.newEvent': '新活动',
    'calendar.today': '今天',
    'calendar.eventDetails': '活动详情',
    'calendar.aboutEvent': '关于此活动',
    'calendar.markCompleted': '标记为已完成',
    'calendar.copyDetails': '复制活动详情',
    'calendar.editEvent': '编辑活动',
    'calendar.deleteEvent': '删除活动',
    'calendar.title': '标题',
    'calendar.dateTime': '日期和时间',
    'calendar.start': '开始',
    'calendar.end': '结束',
    'calendar.eventType': '活动类型',
    'calendar.status': '状态',
    'calendar.location': '地点',
    'calendar.description': '描述',
    'calendar.assignMembers': '分配团队成员',
    'calendar.searchMembers': '按名称搜索...',
    'calendar.cancel': '取消',
    'calendar.create': '创建活动',
    'calendar.update': '更新活动',
    'calendar.guests': '人',
    'calendar.noGuests': '暂无参与者',
    'calendar.invitingTo': '{organizer} 邀请您参加{type}',
    'calendar.linkedLead': '关联线索',
    'calendar.viewInGoogle': '在Google日历中查看',
    'calendar.willSync': '将同步到Google日历',
    'calendar.syncOff': 'Google日历自动同步已关闭',
    'calendar.membersAssigned': '已分配{count}人',
    'calendar.inviteGuests': '邀请参与者',
    'calendar.newEventDesc': '安排新的预约',
    'calendar.editEventDesc': '更新预约详情',
    'calendar.noEvents': '今天没有活动',
    'calendar.upcomingFor': '即将到来的活动',
    'calendar.noMembers': '未找到成员',
    'calendar.reminder': '10分钟前',
    'calendar.nEvents': '{count} 个活动',
    'calendar.invitedBy': '邀请您参加',
    'calendar.noLinkedLead': '无关联线索',
    'calendar.linkLead': '关联线索',
    'integrations.title': '集成和API密钥',
    'integrations.subtitle': '配置外部服务的API凭据。保存的密钥将在运行时由后端使用。',
    'integrations.google': 'Google API',
    'integrations.google.desc': '用于Google日历同步的Client ID和Secret',
    'integrations.google.clientId': 'Client ID',
    'integrations.google.clientSecret': 'Client Secret',
    'integrations.line': 'LINE Messaging API',
    'integrations.line.desc': '用于LINE收件箱的Channel Access Token和Secret',
    'integrations.line.token': 'Channel Access Token',
    'integrations.line.secret': 'Channel Secret',
    'integrations.facebook': 'Facebook Graph API',
    'integrations.facebook.desc': '用于Facebook收件箱的App凭据和Page Token',
    'integrations.facebook.appId': 'App ID',
    'integrations.facebook.appSecret': 'App Secret',
    'integrations.facebook.pageToken': 'Page Access Token',
    'integrations.facebook.pageId': 'Page ID',
    'integrations.instagram': 'Instagram Graph API',
    'integrations.instagram.desc': '用于Instagram收件箱的Business Account ID和Token',
    'integrations.instagram.businessId': 'Business Account ID',
    'integrations.instagram.token': 'Access Token',
    'integrations.saved': 'API密钥已成功保存',
    // Sidebar
    'sidebar.dashboard': '仪表板',
    'sidebar.inbox': '社交收件箱',
    'sidebar.pipeline': '销售管道',
    'sidebar.contacts': '联系人与线索',
    'sidebar.workflows': '工作流',
    'sidebar.tasks': '任务',
    'sidebar.calendar': '日历',
    'sidebar.analytics': '分析',
    'sidebar.settings': '设置',
    'sidebar.mainMenu': '主菜单',
    'sidebar.newDeal': '新交易',
    'sidebar.expand': '展开侧边栏',
    'sidebar.collapse': '折叠侧边栏',
    'sidebar.signOut': '退出登录',
    'sidebar.signOutTitle': '退出登录',
    'sidebar.signOutDesc': '结束当前会话',
    'sidebar.signOutConfirm': '您确定要退出登录吗？',
    'sidebar.signOutDetail': '您需要重新登录才能访问您的管道、联系人和工作流。',
    'sidebar.cancel': '取消',
    'sidebar.q3Goals': 'Q3 目标',
    'sidebar.pipelineForecast': '管道预测已达到每月配额的 {pct}。',
    'sidebar.target': '目标: ${target}',
    // Header
    'header.searchPlaceholder': '搜索交易、联系人、公司...',
    'header.addContact': '添加联系人',
    'header.notifications': '通知',
    'header.markAllRead': '全部标记为已读',
    'header.notif.dealWon': '交易已成交！',
    'header.notif.dealWonDesc': 'Vanguard Pay 签署合同（$210,000 ARR）。',
    'header.notif.automation': 'RelateFlows 自动化',
    'header.notif.automationDesc': '潜在客户评分触发器升级了 David Miller（Apex Global）。',
    'header.notif.meeting': '会议提醒',
    'header.notif.meetingDesc': '明天上午10点与 Catherine Hayes 进行合同审查。',
    // Allocation
    'allocation.title': '分配客户',
    'allocation.customer': '客户',
    'allocation.salesPerson': '销售人员',
    'allocation.selectSales': '选择销售人员...',
    'allocation.projectName': '项目名称',
    'allocation.projectPlaceholder': '例如 RelateFlows Enterprise',
    'allocation.notes': '备注',
    'allocation.notesPlaceholder': '给销售人员的附加备注...',
    'allocation.reallocate': '需要重新分配',
    'allocation.reallocateDesc': '如果选中，将创建新的分配而不是更新现有分配。',
    'allocation.reallocateSameSales': '将创建新分配。之前：{project} → {sales}',
    'allocation.existingActive': '现有活跃分配',
    'allocation.existingActiveDesc': '此客户已分配给 {sales} 项目 "{project}"。',
    'allocation.history': '分配历史',
    'allocation.submitUpdate': '更新分配',
    'allocation.submitCreate': '分配给销售人员',
    'allocation.submitReallocate': '新建分配（重新分配）',
    'allocation.prefilled': '从现有分配预填。如需更改。',
    'allocation.reallocBadge': '重新分配',
    'allocation.statusActive': '活跃',
    'allocation.statusCompleted': '已完成',
    'allocation.statusCancelled': '已取消',
    // Tags
    'tags.title': '管理标签',
    'tags.currentTags': '当前标签',
    'tags.noTags': '尚未分配标签',
    'tags.searchTags': '搜索标签...',
    'tags.allTags': '所有标签',
    'tags.createNew': '创建新标签',
    'tags.createTag': '创建标签',
    'tags.tagName': '标签名称...',
    'tags.cancel': '取消',
    'tags.noTagsFound': '未找到标签。点击下面创建一个。',
    'tags.allAssigned': '所有标签已分配',
    // Inbox
    'inbox.title': '收件箱',
    'inbox.unread': '{count} 未读',
    'inbox.conversations': '{count} / {total} 个对话',
    'inbox.allocated': '已分配',
    'inbox.unassigned': '未分配',
    'inbox.allocate': '分配',
    'inbox.reallocate': '重新分配',
    'inbox.tags': '标签',
    'inbox.replyAs': '以 {name} 身份回复',
    'inbox.typeMessage': '输入消息...',
    'inbox.noProducts': '暂无产品',
    'inbox.addProduct': '添加',
    'inbox.products': '产品',
    'inbox.items': '件',
    'inbox.selectConversation': '选择一个对话',
    'inbox.totalValue': '总价值',
    'inbox.save': '保存',
    'inbox.cancel': '取消',
    'inbox.noCategory': '无分类',
    'inbox.productName': '产品名称',
    'inbox.qty': '数量',
    'inbox.price': '价格',
    'inbox.description': '描述',
    'inbox.notes': '备注',
    'inbox.noProductsHint': '点击"添加"记录客户需求',
    'inbox.unknown': '未知',
    // Tasks
    'tasks.title': '任务',
    'tasks.desc': '管理您的待办事项、跟进和分配。',
    'tasks.openCompleted': '{open} 打开 · {completed} 已完成',
    'tasks.search': '搜索任务...',
    'tasks.filter.all': '全部',
    'tasks.filter.todo': '待办',
    'tasks.filter.inProgress': '进行中',
    'tasks.filter.done': '已完成',
    'tasks.addTask': '添加任务',
    'tasks.column.todo': '待办',
    'tasks.column.inProgress': '进行中',
    'tasks.column.done': '已完成',
    'tasks.empty': '暂无任务',
    'tasks.priority.low': '低',
    'tasks.priority.medium': '中',
    'tasks.priority.high': '高',
    'tasks.modal.newTask': '新任务',
    'tasks.modal.title': '任务标题 *',
    'tasks.modal.description': '描述（可选）',
    'tasks.modal.priority': '优先级',
    'tasks.modal.dueDate': '截止日期',
    'tasks.modal.assignee': '负责人姓名（可选）',
    'tasks.modal.cancel': '取消',
    'tasks.modal.create': '创建任务',
    'tasks.me': '我',
    // Pipeline
    'pipeline.title': '销售管道和看板',
    'pipeline.desc': '管理交易，跨阶段拖拽，并关闭机会。',
    // Contacts
    'contacts.title': '联系人与账户',
    'contacts.desc': '全面的CRM客户列表和潜在客户资格认定。',
    'contacts.directory': '联系人与账户目录',
    'contacts.total': '总联系人: {count} · 高线索评分 (>80): {high} 人',
    'contacts.stage': '阶段:',
    'contacts.stage.all': '所有阶段',
    'contacts.stage.customers': '客户',
    'contacts.stage.opportunities': '商机',
    'contacts.stage.sql': 'SQL (销售合格)',
    'contacts.stage.mql': 'MQL (营销合格)',
    'contacts.stage.leads': '线索',
    'contacts.addContact': '添加联系人',
    'contacts.table.name': '联系人姓名与角色',
    'contacts.table.company': '公司',
    'contacts.table.stage': '生命周期阶段',
    'contacts.table.score': '线索评分',
    'contacts.table.value': '总价值',
    'contacts.table.contacted': '最后联系',
    'contacts.table.actions': '操作',
    'contacts.empty': '未找到符合条件的联系人。',
    'contacts.viewProfile': '查看资料',
    // Dashboard
    'dashboard.pipelineFunnel': '管道漏斗分布',
    'dashboard.pipelineFunnel.desc': '按销售阶段实时分解交易',
    'dashboard.viewKanban': '查看所有看板',
    'dashboard.stage.leadIn': '线索进入',
    'dashboard.stage.contacted': '已联系',
    'dashboard.stage.proposal': '提案',
    'dashboard.stage.negotiation': '谈判',
    'dashboard.stage.closedWon': '已成交',
    'dashboard.stage.closedLost': '已丢失',
    'dashboard.stage.deals': '{v} 个交易',
    'dashboard.topDeals': '高优先级交易',
    'dashboard.winProb': '{prob}% 胜率',
    'dashboard.triggers': 'RelateFlows 触发器',
    'dashboard.manageAll': '管理全部',
    'dashboard.runs': '{count} 次运行',
    'dashboard.recentActivity': '近期CRM活动',
    // Pipeline
    'pipeline.zoom.day': '日',
    'pipeline.zoom.week': '周',
    'pipeline.zoom.month': '月',
    'pipeline.zoom.year': '年',
    'pipeline.zoom.all': '全部',
    'pipeline.viewToggle.kanban': '看板',
    'pipeline.viewToggle.gantt': '甘特图',
    'pipeline.filter.high': '高',
    'pipeline.filter.medium': '中',
    'pipeline.filter.low': '低',
    'pipeline.addDeal': '添加交易',
    'pipeline.gantt': '交易时间线（甘特图）',
    'pipeline.gantt.desc': '点击条形图查看交易详情 · 计划（灰色）与实际（彩色）按阶段进度',
    'pipeline.noDeals': '暂无交易显示',
    'pipeline.plan': '计划（完整时间线）',
    'pipeline.actual': '实际（阶段进度）',
    'pipeline.progress': '进度 = 当前阶段位置 / 总阶段数',
    'pipeline.dropHere': '将交易拖放到此处',
    'pipeline.tooltip.company': '公司',
    'pipeline.tooltip.value': '价值',
    'pipeline.tooltip.contact': '联系人',
    'pipeline.tooltip.stage': '阶段',
    // Analytics
    'analytics.totalArr': '总管道ARR',
    'analytics.yoyGrowth': '+18.4% 同比增长',
    'analytics.closedWon': '已成交收入',
    'analytics.q3Target': 'Q3目标的60%',
    'analytics.winRate': '总体胜率',
    'analytics.benchmark': '基准: 25%',
    'analytics.cycleLength': '销售周期长度',
    'analytics.cycleDays': '21天',
    'analytics.faster': '使用RelateFlows快4天',
    'analytics.monthlyRevenue': '月度收入与预测',
    'analytics.monthlyRevenue.desc': '历史表现与Q3预测分解',
    'analytics.q3': '2026年Q3',
    'analytics.leadSource': '线索来源归因',
    'analytics.leaderboard': '销售团队排行榜（Q3）',
    'analytics.dealsWon': '{count} 个成交交易',
    // CS Queue
    'sidebar.csQueue': 'CS队列',
    'page.csQueue': 'CS队列',
    'page.csQueue.desc': '客户支持聊天队列和团队管理',
    'csQueue.title': '客户支持队列',
    'csQueue.subtitle': '{waiting} 等待 · {active} 活跃',
    'csQueue.userInfo': '{name} · {role}',
    'csQueue.failedClaim': '认领聊天失败',
    'csQueue.tab.queue': '队列 ({count})',
    'csQueue.tab.myChats': '我的聊天 ({count})',
    'csQueue.tab.team': '团队 ({count} 在线)',
    'csQueue.tab.performance': '绩效',
    'csQueue.refresh': '刷新',
    'csQueue.closeChat': '关闭聊天',
    'csQueue.noMessages': '暂无消息',
    'csQueue.typeResponse': '输入您的回复...',
    'csQueue.status.all': '全部',
    'csQueue.status.waiting': '等待中',
    'csQueue.status.assigned': '已分配',
    'csQueue.status.active': '活跃',
    'csQueue.status.closed': '已关闭',
    'csQueue.sessions': '{count} 个会话',
    'csQueue.queueEmpty': '队列中无聊天',
    'csQueue.view': '查看',
    'csQueue.claim': '认领',
    'csQueue.myChatsEmpty': '没有分配给您的活跃聊天',
    'csQueue.messages': '{count} 条消息',
    'csQueue.open': '打开',
    'csQueue.online': '在线',
    'csQueue.offline': '离线',
    'csQueue.activeChats': '活跃聊天',
    'csQueue.todaySchedule': "今日安排",
    'csQueue.dayOff': '休息日',
    'csQueue.noTeam': '未找到CS团队成员',
    'csQueue.performance': '过去7天绩效',
    'csQueue.table.agent': '客服',
    'csQueue.table.totalChats': '总聊天数',
    'csQueue.table.responded': '已回复',
    'csQueue.table.avgResponse': '平均回复时间',
    'csQueue.table.closed': '已关闭',
    'csQueue.table.hoursSpent': '花费时间',
    'csQueue.min': '{count} 分钟',
    'csQueue.hrs': '{count} 小时',
    'csQueue.unknown': '未知',
    'csQueue.noPerformance': '暂无绩效数据',
  },
};

const storageKey = (userId: string) => `rf-settings-${userId}`;

const SettingsContext = createContext<SettingsContextType | undefined>(undefined);

export const SettingsProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const { user } = useAuth();
  const userId = user?.id || 'anonymous';
  const [prevUserId, setPrevUserId] = useState(userId);

  const loadSettings = (uid: string): UserSettings => {
    try {
      const saved = localStorage.getItem(storageKey(uid));
      if (saved) {
        const parsed = JSON.parse(saved);
        // Don't load integrations from localStorage — they're fetched from API
        return {
          ...DEFAULT_SETTINGS,
          ...parsed,
          integrations: { ...DEFAULT_INTEGRATIONS },
        };
      }
    } catch {/* ignore corrupt data */}
    return DEFAULT_SETTINGS;
  };

  const [settings, setSettings] = useState<UserSettings>(() => loadSettings(userId));

  const [savedSuccess, setSavedSuccess] = useState(false);
  const [resolvedTheme, setResolvedTheme] = useState<'light' | 'dark'>('light');

  // Load integration keys from server on mount and when user changes
  const integrationsLoaded = useRef(false);
  const loadServerIntegrations = async () => {
    try {
      const data = await api.get<Record<string, string>>('/api/settings/integrations');
      setSettings((prev) => ({
        ...prev,
        integrations: { ...DEFAULT_INTEGRATIONS, ...data },
      }));
    } catch {
      // Server not reachable or no tenant — use defaults
    }
  };

  // Reload settings when user changes (during render, not effect)
  if (userId !== prevUserId) {
    setPrevUserId(userId);
    setSettings(loadSettings(userId));
    integrationsLoaded.current = false;
  }

  useEffect(() => {
    if (!integrationsLoaded.current && user) {
      integrationsLoaded.current = true;
      loadServerIntegrations();
    }
  }, [user]);

  useEffect(() => {
    const mediaQuery = window.matchMedia('(prefers-color-scheme: dark)');
    const updateResolved = () => {
      const resolved = settings.theme === 'system' ? (mediaQuery.matches ? 'dark' : 'light') : settings.theme;
      setResolvedTheme(resolved);
      document.documentElement.classList.toggle('dark', resolved === 'dark');
      document.documentElement.setAttribute('data-theme', resolved === 'dark' ? 'dark' : 'light');
    };
    updateResolved();
    mediaQuery.addEventListener('change', updateResolved);
    return () => mediaQuery.removeEventListener('change', updateResolved);
  }, [settings.theme]);

  const persist = (updated: UserSettings) => {
    // Only persist non-sensitive settings to localStorage
    const { integrations, ...safe } = updated;
    localStorage.setItem(storageKey(userId), JSON.stringify(safe));
  };

  const setTheme = (theme: ThemeMode) => {
    setSettings((prev) => ({ ...prev, theme }));
  };

  const setLanguage = (language: Language) => {
    setSettings((prev) => ({ ...prev, language }));
  };

  const setPrimaryColor = (primaryColor: string) => {
    setSettings((prev) => ({ ...prev, primaryColor }));
  };

  const setAccentColor = (accentColor: string) => {
    setSettings((prev) => ({ ...prev, accentColor }));
  };

  const setIntegrationKey = (key: keyof IntegrationKeys, value: string) => {
    setSettings((prev) => ({
      ...prev,
      integrations: { ...prev.integrations, [key]: value },
    }));
  };

  const saveSettings = async () => {
    persist(settings);
    // Save integration keys server-side (encrypted)
    try {
      await api.put('/api/settings/integrations', { keys: settings.integrations });
    } catch (err) {
      console.error('Failed to save integration keys to server:', err);
    }
    setSavedSuccess(true);
    setTimeout(() => setSavedSuccess(false), 3000);
  };

  const t = (key: string): string => {
    return translations[settings.language][key] || translations.en[key] || key;
  };

  return (
    <SettingsContext.Provider
      value={{
        settings,
        theme: settings.theme,
        setTheme,
        resolvedTheme,
        language: settings.language,
        setLanguage,
        primaryColor: settings.primaryColor,
        setPrimaryColor,
        accentColor: settings.accentColor,
        setAccentColor,
        integrations: settings.integrations,
        setIntegrationKey,
        t,
        saveSettings,
        savedSuccess,
      }}
    >
      {children}
    </SettingsContext.Provider>
  );
};

export const useSettings = () => {
  const context = useContext(SettingsContext);
  if (!context) throw new Error('useSettings must be used within a SettingsProvider');
  return context;
};
